### ISSUE TITLE
Brain Extraction

### ISSUE THREAD

**Issue by Niko-k98** [BrainLesion/preprocessing#55]
Is the Brain extraction and masking  currently functional in this repo or should I stick to the BraTS tool-kit repo for the time being?

**Comment by neuronflow** [comment]
It is functional. However, the documentation and tutorials still need to be prepared.

 What is the issue you are facing?
 
 
You can use the package like this:
https://github.com/BrainLesion/preprocessing/blob/main/example_modality_centric_preprocessor.py

For brain extraction, set `bet` to `True` for each modality you want to skullstrip.

**Comment by Niko-k98** [comment]
I just wanted to verify functionality. So I should format my data like example_data? and do the MR files need to be in .nii.gz? Thank you for your assistance

**Comment by neuronflow** [comment]
so far I tested the pipeline with `.nii.gz` files. No experience with `nrrd` yet.

You can use any file structure you want. You just need to provide input and output paths.

Output files will have the resolution of the SRI24 atlas:
`155x240x240`

**Comment by neuronflow** [comment]
closed until more information is provided.

**Comment by neuronflow** [comment]
@Niko-k98 
we now have some API changes and a first small tutorial:
https://github.com/BrainLesion/tutorials/tree/main/preprocessing

Your feedback is appreciated :)
