### ISSUE TITLE
Preprocessing does not run on Windows - FileNotFoundError

### ISSUE THREAD

**Issue by evamariie** [BrainLesion/preprocessing#70]
Preprocessing does not run on Windows -> FileNotFoundError (log attached)

[BraTS-Toolkit_Error.txt](https://github.com/BrainLesion/preprocessing/files/14594554/BraTS-Toolkit_Error.txt)

**Comment by neuronflow** [comment]
This will probably require changes here: https://github.com/BrainLesion/HD-BET

**Comment by MarcelRosier** [comment]
should be fixed by https://github.com/BrainLesion/HD-BET/pull/2, closing
